apiVersion: apps/v1
kind: Deployment
metadata:
  name: contractservice
  namespace: contractservice
  labels:
    app: contractservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contractservice
  template:
    metadata:
      labels:
        app: contractservice
    spec:
      containers:
        - name: contractservice
          image: <ecr-url>/contractservice:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          securityContext:
            allowPrivilegeEscalation: false