spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectionpool: true
          poolsize: 2
          quitwait: false
          timeout: 5000
          connection-timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        session:
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

cloud:
  aws:
    s3:
      bucket: ${KEYSTORE_BUCKET}

service:
  user:
    url: https://picktartup.com
  startup:
    url: https://picktartup.com
  wallet:
    url: https://192.168.0.141:31158/wallet
