spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  user:
    url: http://192.168.0.143:32450/user
  startup:
    url: http://192.168.0.143:32450/startup
  wallet:
    url: http://192.168.0.143:32450/wallet
